/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.BookController;
import Controllers.PaymentController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Duc Dung Dan
 */
public class Payment extends javax.swing.JPanel {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        returnBook = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        detail = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        payment = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        informationRent = new javax.swing.JTable();
        inputSearch = new javax.swing.JTextField();
        typeSearch = new javax.swing.JComboBox();
        search = new javax.swing.JButton();
        prev = new javax.swing.JButton();
        page = new javax.swing.JLabel();
        next = new javax.swing.JButton();

        returnBook.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        returnBook.setText("Trả sách");
        returnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookActionPerformed(evt);
            }
        });
        jPopupMenu1.add(returnBook);

        jMenu1.setText("Hiển thị");

        buttonGroup1.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Tất cả");
        jRadioButtonMenuItem2.setFocusPainted(true);
        jRadioButtonMenuItem2.setFocusable(true);
        jRadioButtonMenuItem2.setRolloverEnabled(true);
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem2);

        buttonGroup1.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonMenuItem1.setText("Đang mượn");
        jRadioButtonMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonMenuItem1.setFocusPainted(true);
        jRadioButtonMenuItem1.setFocusable(true);
        jRadioButtonMenuItem1.setRolloverEnabled(true);
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1);

        buttonGroup1.add(jRadioButtonMenuItem3);
        jRadioButtonMenuItem3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonMenuItem3.setText("Đã trả");
        jRadioButtonMenuItem3.setFocusPainted(true);
        jRadioButtonMenuItem3.setFocusable(true);
        jRadioButtonMenuItem3.setRolloverEnabled(true);
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem3);

        buttonGroup1.add(jRadioButtonMenuItem4);
        jRadioButtonMenuItem4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonMenuItem4.setText("Quá hạn");
        jRadioButtonMenuItem4.setFocusPainted(true);
        jRadioButtonMenuItem4.setFocusable(true);
        jRadioButtonMenuItem4.setRolloverEnabled(true);
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem4);

        jPopupMenu1.add(jMenu1);

        detail.setText("Chi tiết");
        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });
        jPopupMenu1.add(detail);

        payment.setBackground(new java.awt.Color(233, 235, 238));

        informationRent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idRent", "idBook", "Tên sách", "idUser", "Email", "Tên người dùng", "Ngày mươn", "Ngày dự kiến trả", "Ngày trả", "Tiền mượn", "Tiền phạt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        informationRent.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        informationRent.setGridColor(new java.awt.Color(233, 235, 238));
        informationRent.getTableHeader().setReorderingAllowed(false);
        informationRent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informationRentMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                informationRentMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(informationRent);
        if (informationRent.getColumnModel().getColumnCount() > 0) {
            informationRent.getColumnModel().getColumn(0).setResizable(false);
            informationRent.getColumnModel().getColumn(0).setPreferredWidth(60);
            informationRent.getColumnModel().getColumn(1).setResizable(false);
            informationRent.getColumnModel().getColumn(1).setPreferredWidth(60);
            informationRent.getColumnModel().getColumn(2).setResizable(false);
            informationRent.getColumnModel().getColumn(2).setPreferredWidth(150);
            informationRent.getColumnModel().getColumn(3).setResizable(false);
            informationRent.getColumnModel().getColumn(3).setPreferredWidth(60);
            informationRent.getColumnModel().getColumn(4).setResizable(false);
            informationRent.getColumnModel().getColumn(4).setPreferredWidth(120);
            informationRent.getColumnModel().getColumn(5).setResizable(false);
            informationRent.getColumnModel().getColumn(5).setPreferredWidth(90);
            informationRent.getColumnModel().getColumn(6).setResizable(false);
            informationRent.getColumnModel().getColumn(6).setPreferredWidth(90);
            informationRent.getColumnModel().getColumn(7).setResizable(false);
            informationRent.getColumnModel().getColumn(7).setPreferredWidth(90);
            informationRent.getColumnModel().getColumn(8).setResizable(false);
            informationRent.getColumnModel().getColumn(8).setPreferredWidth(90);
            informationRent.getColumnModel().getColumn(9).setResizable(false);
            informationRent.getColumnModel().getColumn(9).setPreferredWidth(70);
            informationRent.getColumnModel().getColumn(10).setResizable(false);
            informationRent.getColumnModel().getColumn(10).setPreferredWidth(70);
        }

        typeSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "idRent", "idBook", "Tên sách", "idUser", "Email", "Tên người dùng", "Ngày mượn", "Ngày trả" }));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Search.png"))); // NOI18N
        search.setBorderPainted(false);
        search.setContentAreaFilled(false);
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/prev.png"))); // NOI18N
        prev.setBorderPainted(false);
        prev.setContentAreaFilled(false);
        prev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });

        page.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        page.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        page.setText("0");

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/next.png"))); // NOI18N
        next.setContentAreaFilled(false);
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paymentLayout = new javax.swing.GroupLayout(payment);
        payment.setLayout(paymentLayout);
        paymentLayout.setHorizontalGroup(
            paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentLayout.createSequentialGroup()
                .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paymentLayout.createSequentialGroup()
                        .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(page, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(paymentLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(typeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paymentLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        paymentLayout.setVerticalGroup(
            paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSearch)
                    .addComponent(typeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(next, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(page, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(prev))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void informationRentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informationRentMouseReleased
        DefaultTableModel model = (DefaultTableModel) informationRent.getModel();
        int selectRow = informationRent.getSelectedRow();
        if (selectRow != -1 && evt.isPopupTrigger()) {
            jPopupMenu1.show(informationRent, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_informationRentMouseReleased

    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        PaymentController.prevTablePayment(informationRent, page);
    }//GEN-LAST:event_prevActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        PaymentController.nextTablePayment(informationRent, page);
    }//GEN-LAST:event_nextActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        PaymentController.searchTablePayment(informationRent, page, inputSearch.getText() == null ? "" : inputSearch.getText(), typeSearch.getSelectedItem().toString());
    }//GEN-LAST:event_searchActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        PaymentController.showTablePayment(informationRent, page, "all");
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        PaymentController.showTablePayment(informationRent, page, "renting");
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        PaymentController.showTablePayment(informationRent, page, "rented");
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void jRadioButtonMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem4ActionPerformed
        PaymentController.showTablePayment(informationRent, page, "out of date");
    }//GEN-LAST:event_jRadioButtonMenuItem4ActionPerformed

    private void returnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookActionPerformed
        DefaultTableModel model = (DefaultTableModel) informationRent.getModel();
        int selectRow = informationRent.getSelectedRow();
        String question = "Bạn muốn trả sách có idRent = " + model.getValueAt(selectRow, 0) + ", idBook = " + model.getValueAt(selectRow, 1) + ", idUser = " + model.getValueAt(selectRow, 3);
        if (selectRow != -1 && JOptionPane.showConfirmDialog(null, question, "Thông báo", 2) == 0) {
            PaymentController.returnBook((int) model.getValueAt(selectRow, 0), (int) model.getValueAt(selectRow, 1), (int) model.getValueAt(selectRow, 10));
        }
    }//GEN-LAST:event_returnBookActionPerformed

    private void informationRentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informationRentMouseClicked
        DefaultTableModel model = (DefaultTableModel) informationRent.getModel();
        int selectRow = informationRent.getSelectedRow();
        if(selectRow != -1 && model.getValueAt(selectRow, 8) == null) {
            returnBook.setVisible(true);
        } else {
            returnBook.setVisible(false);
        }
    }//GEN-LAST:event_informationRentMouseClicked

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailActionPerformed
        DefaultTableModel model = (DefaultTableModel) informationRent.getModel();
        int selectRow = informationRent.getSelectedRow();
        if (selectRow != -1) {
            BookController.viewBook((Number) informationRent.getValueAt(selectRow, 1));
        }
    }//GEN-LAST:event_detailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JMenuItem detail;
    public javax.swing.JTable informationRent;
    public javax.swing.JTextField inputSearch;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JPopupMenu jPopupMenu1;
    public javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    public javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    public javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    public javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton next;
    public static javax.swing.JLabel page;
    public javax.swing.JPanel payment;
    public javax.swing.JButton prev;
    public javax.swing.JMenuItem returnBook;
    public javax.swing.JButton search;
    public javax.swing.JComboBox typeSearch;
    // End of variables declaration//GEN-END:variables
}
