/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import Controllers.MainController;
import Controllers.StatisticalController;
import Models.BookModel;
import Models.DataInterface;
import Models.RentBookModel;
import Models.UserModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;

/**
 *
 * @author Duc Dung Dan
 */
public class Statistical extends javax.swing.JPanel {

    /**
     * Creates new form Statistical
     */
    public Statistical() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.ButtonGroup();
        book = new javax.swing.ButtonGroup();
        rent = new javax.swing.ButtonGroup();
        Statistics = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        TKUser = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        statisticalUser = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        titleUser = new javax.swing.JLabel();
        statisticalDateUser = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        statisticalSignUser = new javax.swing.JLabel();
        statisticalAdress = new javax.swing.JRadioButton();
        statisticalAge = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        TKBook = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        statisticalBook = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        titleBook = new javax.swing.JLabel();
        statisticalDateBook = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        statisticalSignBook = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        statisticsPublished = new javax.swing.JRadioButton();
        publishersStatistics = new javax.swing.JRadioButton();
        authorStatistics = new javax.swing.JRadioButton();
        statisticalCategory = new javax.swing.JRadioButton();
        jButton8 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        statisticsDayborrow = new javax.swing.JRadioButton();
        statisticsDayreturn = new javax.swing.JRadioButton();
        statisticsIdBook = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        TKRent = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        statisticalRent = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        titleRent = new javax.swing.JLabel();
        statisticalDateRent = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        statisticalSignRent = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        Statistics.setBackground(new java.awt.Color(233, 235, 238));

        jTabbedPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabbedPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel13AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        TKUser.setBackground(new java.awt.Color(255, 255, 255));
        TKUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        statisticalUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Địa chỉ", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        statisticalUser.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane6.setViewportView(statisticalUser);
        if (statisticalUser.getColumnModel().getColumnCount() > 0) {
            statisticalUser.getColumnModel().getColumn(0).setPreferredWidth(95);
            statisticalUser.getColumnModel().getColumn(1).setPreferredWidth(400);
            statisticalUser.getColumnModel().getColumn(2).setPreferredWidth(140);
        }

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("THƯ VIỆN ONLINE CONVENIENT");

        titleUser.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        titleUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleUser.setText("THỐNG KÊ NGƯỜI DÙNG THEO ĐỊA CHỈ");

        statisticalDateUser.setText("Hà Nội, ngày ... tháng ... năm ...");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Người lập bảng");

        statisticalSignUser.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        statisticalSignUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statisticalSignUser.setText("Ký tên");

        javax.swing.GroupLayout TKUserLayout = new javax.swing.GroupLayout(TKUser);
        TKUser.setLayout(TKUserLayout);
        TKUserLayout.setHorizontalGroup(
            TKUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TKUserLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(TKUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addComponent(titleUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TKUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TKUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statisticalDateUser, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(statisticalSignUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        TKUserLayout.setVerticalGroup(
            TKUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TKUserLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleUser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statisticalDateUser)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(statisticalSignUser)
                .addGap(25, 25, 25))
        );

        user.add(statisticalAdress);
        statisticalAdress.setText("Địa chỉ");

        user.add(statisticalAge);
        statisticalAge.setText("Độ tuổi");

        jButton1.setText("Thống kê");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Export to PDF");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TKUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(statisticalAdress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statisticalAge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statisticalAdress)
                    .addComponent(statisticalAge)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TKUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Người dùng", jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel14AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        TKBook.setBackground(new java.awt.Color(255, 255, 255));
        TKBook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        statisticalBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Thể loại", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        statisticalBook.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane8.setViewportView(statisticalBook);
        if (statisticalBook.getColumnModel().getColumnCount() > 0) {
            statisticalBook.getColumnModel().getColumn(0).setResizable(false);
            statisticalBook.getColumnModel().getColumn(0).setPreferredWidth(95);
            statisticalBook.getColumnModel().getColumn(1).setPreferredWidth(400);
            statisticalBook.getColumnModel().getColumn(2).setResizable(false);
            statisticalBook.getColumnModel().getColumn(2).setPreferredWidth(140);
        }

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("THƯ VIỆN ONLINE CONVENIENT");

        titleBook.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        titleBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleBook.setText("THỐNG KÊ SÁCH THEO THỂ LOẠI");

        statisticalDateBook.setText("Hà Nội, ngày ... tháng ... năm ...");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Người lập bảng");

        statisticalSignBook.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        statisticalSignBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statisticalSignBook.setText("Ký tên");

        javax.swing.GroupLayout TKBookLayout = new javax.swing.GroupLayout(TKBook);
        TKBook.setLayout(TKBookLayout);
        TKBookLayout.setHorizontalGroup(
            TKBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TKBookLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(TKBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TKBookLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TKBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statisticalDateBook, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(statisticalSignBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        TKBookLayout.setVerticalGroup(
            TKBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TKBookLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleBook, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statisticalDateBook)
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(statisticalSignBook)
                .addGap(25, 25, 25))
        );

        jButton6.setText("Thống kê");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        book.add(statisticsPublished);
        statisticsPublished.setText("Năm XB");

        book.add(publishersStatistics);
        publishersStatistics.setText("Nhà XB");

        book.add(authorStatistics);
        authorStatistics.setText("Tác giả");

        book.add(statisticalCategory);
        statisticalCategory.setText("Thể loại");

        jButton8.setText("Export to PDF");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TKBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(statisticalCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(authorStatistics)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(publishersStatistics)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statisticsPublished)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(statisticsPublished)
                    .addComponent(publishersStatistics)
                    .addComponent(authorStatistics)
                    .addComponent(statisticalCategory)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TKBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jTabbedPane2.addTab("Sách", jPanel14);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel16AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        rent.add(statisticsDayborrow);
        statisticsDayborrow.setText("Ngày mượn");

        rent.add(statisticsDayreturn);
        statisticsDayreturn.setText("Ngày trả");

        rent.add(statisticsIdBook);
        statisticsIdBook.setText("IdBook");
        statisticsIdBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsIdBookActionPerformed(evt);
            }
        });

        jButton7.setText("Thống kê");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        TKRent.setBackground(new java.awt.Color(255, 255, 255));
        TKRent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        statisticalRent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Ngày mượn", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        statisticalRent.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane9.setViewportView(statisticalRent);
        if (statisticalRent.getColumnModel().getColumnCount() > 0) {
            statisticalRent.getColumnModel().getColumn(0).setPreferredWidth(95);
            statisticalRent.getColumnModel().getColumn(1).setPreferredWidth(400);
            statisticalRent.getColumnModel().getColumn(2).setPreferredWidth(140);
        }

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("THƯ VIỆN ONLINE CONVENIENT");

        titleRent.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        titleRent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleRent.setText("THỐNG KÊ MƯỢN TRẢ THEO NGÀY MƯỢN");

        statisticalDateRent.setText("Hà Nội, ngày ... tháng ... năm ...");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Người lập bảng");

        statisticalSignRent.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        statisticalSignRent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statisticalSignRent.setText("Ký tên");

        javax.swing.GroupLayout TKRentLayout = new javax.swing.GroupLayout(TKRent);
        TKRent.setLayout(TKRentLayout);
        TKRentLayout.setHorizontalGroup(
            TKRentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TKRentLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(TKRentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleRent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TKRentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TKRentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statisticalDateRent, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(statisticalSignRent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        TKRentLayout.setVerticalGroup(
            TKRentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TKRentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleRent, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statisticalDateRent)
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(statisticalSignRent)
                .addGap(25, 25, 25))
        );

        jButton9.setText("Export to PDF");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(statisticsDayborrow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statisticsDayreturn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statisticsIdBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap(108, Short.MAX_VALUE)
                        .addComponent(TKRent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(statisticsIdBook)
                    .addComponent(statisticsDayreturn)
                    .addComponent(statisticsDayborrow)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TKRent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jTabbedPane2.addTab("Mượn trả", jPanel16);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("THỐNG KÊ");

        javax.swing.GroupLayout StatisticsLayout = new javax.swing.GroupLayout(Statistics);
        Statistics.setLayout(StatisticsLayout);
        StatisticsLayout.setHorizontalGroup(
            StatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatisticsLayout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jTabbedPane2)
        );
        StatisticsLayout.setVerticalGroup(
            StatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatisticsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Statistics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Statistics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JTableHeader staUser = statisticalUser.getTableHeader();
        TableColumnModel staUsercolumns = staUser.getColumnModel();
        Date date = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("dd MM yyyy");
        String[] stringDate = ft.format(date).split(" ");
        statisticalDateUser.setText("Hà Nội, ngày " + stringDate[0] + " tháng " + stringDate[1] + " năm " + stringDate[2]);
        statisticalSignUser.setText(UserModel.user.getName());
        DataInterface getStatisticalData = new UserModel();
        if (statisticalAdress.isSelected()) {
            titleUser.setText("THỐNG KÊ NGƯỜI DÙNG THEO ĐỊA CHỈ");
            StatisticalController.statistics(statisticalUser, new String[]{"STT", "Địa chỉ", "Số lượng"}, new String[]{"City", "COUNT(*)"}, getStatisticalData);
        } else {
            titleUser.setText("THỐNG KÊ NGƯỜI DÙNG THEO ĐỘ TUỔI");
            StatisticalController.statistics(statisticalUser, new String[]{"STT", "Độ tuổi", "Số lượng"}, new String[]{"YEAR(CURDATE()) - YEAR(Date_of_Birth)", "COUNT(*)"}, getStatisticalData);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showSaveDialog(this);
        MainController.exportPDF(fc.getSelectedFile().toString(), titleUser.getText(), statisticalUser);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel13AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel13AncestorAdded
        statisticalAdress.setSelected(true);
    }//GEN-LAST:event_jPanel13AncestorAdded

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JTableHeader staBook = statisticalBook.getTableHeader();
        TableColumnModel staBookcolumns = staBook.getColumnModel();
        Date date = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("dd MM yyyy");
        String[] stringDate = ft.format(date).split(" ");
        statisticalDateBook.setText("Hà Nội, ngày " + stringDate[0] + " tháng " + stringDate[1] + " năm " + stringDate[2]);
        statisticalSignBook.setText(UserModel.user.getName());
        DataInterface getStatisticalData =  new BookModel();
        if (statisticalCategory.isSelected()) {
            titleBook.setText("THỐNG KÊ SÁCH THEO THỂ LOẠI");
            StatisticalController.statistics(statisticalBook, new String[] {"STT", "Thể loại", "Số lượng"},new String[] {"Type", "COUNT(*)"}, getStatisticalData);
        } else {
            if(authorStatistics.isSelected()) {
                titleBook.setText("THỐNG KÊ SÁCH THEO TÁC GIẢ");
                StatisticalController.statistics(statisticalBook, new String[]{"STT", "Tác giả", "Số lượng"}, new String[]{"Author", "COUNT(*)"}, getStatisticalData);
            } else {
                if(publishersStatistics.isSelected()) {
                    titleBook.setText("THỐNG KÊ SÁCH THEO NHÀ XUẤT BẢN");
                    StatisticalController.statistics(statisticalBook, new String[]{"STT", "Nhà xuất bản", "Số lượng"}, new String[]{"Publishing_company", "COUNT(*)"}, getStatisticalData);
                } else {
                    titleBook.setText("THỐNG KÊ SÁCH THEO NĂM XUẤT BẢN");
                    StatisticalController.statistics(statisticalBook, new String[]{"STT", "Năm xuất bản", "Số lượng"}, new String[]{"Publishing_year", "COUNT(*)"}, getStatisticalData);
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showSaveDialog(this);
        MainController.exportPDF(fc.getSelectedFile().toString(), titleBook.getText(), statisticalUser);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jPanel14AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel14AncestorAdded
        statisticalCategory.setSelected(true);
    }//GEN-LAST:event_jPanel14AncestorAdded

    private void statisticsIdBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsIdBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statisticsIdBookActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Date date = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("dd MM yyyy");
        String[] stringDate = ft.format(date).split(" ");
        statisticalDateRent.setText("Hà Nội, ngày " + stringDate[0] + " tháng " + stringDate[1] + " năm " + stringDate[2]);
        statisticalSignRent.setText(UserModel.user.getName());
        DataInterface getStatisticalData = new RentBookModel();
        if (statisticsDayborrow.isSelected()) {
            titleRent.setText("THỐNG KÊ MƯỢN TRẢ THEO NGÀY MƯỢN");
            StatisticalController.statistics(statisticalRent, new String[]{"STT", "Ngày mượn", "Số lượng"}, new String[]{"Day_borrow", "COUNT(*)"}, getStatisticalData);
        } else {
            if (statisticsDayreturn.isSelected()) {
                titleRent.setText("THỐNG KÊ MƯỢN TRẢ THEO NGÀY TRẢ");
                StatisticalController.statistics(statisticalRent, new String[]{"STT", "Ngày trả", "Số lượng"}, new String[]{"Day_return", "COUNT(*)"}, getStatisticalData);
            } else {
                titleRent.setText("THỐNG KÊ MƯỢN TRẢ THEO MÃ SÁCH");
                StatisticalController.statistics(statisticalRent, new String[]{"STT", "idBook", "Số lượng mượn"}, new String[]{"idBook", "COUNT(*)"}, getStatisticalData);
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showSaveDialog(this);
        MainController.exportPDF(fc.getSelectedFile().toString(), titleRent.getText(), statisticalUser);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jPanel16AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel16AncestorAdded
        statisticsDayborrow.setSelected(true);
    }//GEN-LAST:event_jPanel16AncestorAdded

    private void jTabbedPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPane2AncestorAdded

    }//GEN-LAST:event_jTabbedPane2AncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Statistics;
    private javax.swing.JPanel TKBook;
    private javax.swing.JPanel TKRent;
    private javax.swing.JPanel TKUser;
    private javax.swing.JRadioButton authorStatistics;
    private javax.swing.ButtonGroup book;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JRadioButton publishersStatistics;
    private javax.swing.ButtonGroup rent;
    private javax.swing.JRadioButton statisticalAdress;
    private javax.swing.JRadioButton statisticalAge;
    private javax.swing.JTable statisticalBook;
    private javax.swing.JRadioButton statisticalCategory;
    private javax.swing.JLabel statisticalDateBook;
    private javax.swing.JLabel statisticalDateRent;
    private javax.swing.JLabel statisticalDateUser;
    private javax.swing.JTable statisticalRent;
    private javax.swing.JLabel statisticalSignBook;
    private javax.swing.JLabel statisticalSignRent;
    private javax.swing.JLabel statisticalSignUser;
    private javax.swing.JTable statisticalUser;
    private javax.swing.JRadioButton statisticsDayborrow;
    private javax.swing.JRadioButton statisticsDayreturn;
    private javax.swing.JRadioButton statisticsIdBook;
    private javax.swing.JRadioButton statisticsPublished;
    private javax.swing.JLabel titleBook;
    private javax.swing.JLabel titleRent;
    private javax.swing.JLabel titleUser;
    private javax.swing.ButtonGroup user;
    // End of variables declaration//GEN-END:variables
}
